In [1]:
pip install pandas

In [2]:
pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
accelerate                       0.33.0
aiohappyeyeballs                 2.4.0
aiohttp                          3.10.5
aiosignal                        1.3.1
alabaster                        0.7.16
albucore                         0.0.14
albumentations                   1.4.14
altair                           4.2.2
annotated-types                  0.7.0
anyio                            3.7.1
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array_record                     0.5.1
arviz                            0.18.0
asn1crypto                       1.5.1
astropy                          6.1.3
astropy-iers-data                0.2024.8.27.10.28.29
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.1.0
attrs                            24.2.0
audioread             

In [3]:
import pandas as pd

# Panda Series
Single coulumn data so can be created from list. Pandas series object corresponds to the one-dimensional structure of NumPy


In [4]:
products=['A','B','C','D']
print(products)
type(products)

['A', 'B', 'C', 'D']


list

In [5]:
product_categories=pd.Series(products)
print(product_categories)
type(product_categories)

0    A
1    B
2    C
3    D
dtype: object


pandas.core.series.Series

The left column is showing the index of the elements. Here the index and datatype has been stored

In [6]:
daily_rates_dollars=pd.Series([40,45,50,60])
print(daily_rates_dollars)

0    40
1    45
2    50
3    60
dtype: int64


NumPy is used for numeric data only
Pandas is used for both numeric and non numeric data

In [7]:
import numpy as np

In [8]:
array_a=np.array([10,20,30,40,50])
print(array_a)
type(array_a)

[10 20 30 40 50]


numpy.ndarray

In [9]:
#converting the numpy ndaray to pandas series:
series_a=pd.Series(array_a)
print(series_a)
print(type(series_a))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>


# Working with attributes
Attribute is avariable providing metadata about an object. It is passive which means can only provide data
Method-a function that can be associated with an object. this is active as we can do some things with this

In [10]:
series_a.dtype #finding datatype


dtype('int64')

In [11]:
series_a.size #gives no. of elemets

5

In [12]:
product_categories.dtype #O is used for non-numeric data

dtype('O')

In [13]:
#If we want toassign any name to a obtained object, we can use assignment operator
product_categories.name='Product Categories'
print(product_categories.name)

Product Categories


# Index in Pandas
The approach shown will be applicable to dataframe and other objects also. Indexing gives faster acces to all the data. Index itslef is a adatastructure here.

In [14]:
prices_per_category={'Product A':22250,'Product B':16600,'Product C':15600} #first made a dictionary
print(prices_per_category)
print(type(prices_per_category))

{'Product A': 22250, 'Product B': 16600, 'Product C': 15600}
<class 'dict'>


In [15]:
prices_per_category=pd.Series(prices_per_category)
print(type(prices_per_category))

<class 'pandas.core.series.Series'>


In [16]:
print(prices_per_category.index) #index values will be corresponding to the integer values
type(prices_per_category.index)

Index(['Product A', 'Product B', 'Product C'], dtype='object')


pandas.core.indexes.base.Index

Panda Series index represens a very solid datastrucutre: both Explicit and Implicit. By default Pandas assign 0 based indexing(also called Implicit Indexing)

In [17]:
series_a.index #here the index is range type strucute. This is position based indexing. This is called 0 based indexing

RangeIndex(start=0, stop=5, step=1)

In [18]:
list(series_a.index)

[0, 1, 2, 3, 4]

In [19]:
prices_per_category.index # this is label based indexing. this is also explicit indixing as the labels were created externally from dictionary. this is good for data visualization and meaningful name

Index(['Product A', 'Product B', 'Product C'], dtype='object')

In [20]:
type(prices_per_category.index)

pandas.core.indexes.base.Index

In [21]:
#obtaining elements from indexing:
print(series_a[0])
print(prices_per_category['Product A'])
print(prices_per_category[0]) #can be ued by default implicit indexing also

10
22250
22250


<ipython-input-21-59eb74c7838f>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(prices_per_category[0]) #can be ued by default implicit indexing also


Using Explicit indexing amnually:

In [22]:
series_b=pd.Series([10,20,30,40,50],index=[1,2,3,4,5])
print(series_b)
print(series_b[1]) #here starting index will be 1

1    10
2    20
3    30
4    40
5    50
dtype: int64
10


In [23]:
series_c=pd.Series([10,20,30,40,50],index=["1","2","3","4","5"]) #using strings as labels
print(series_c["1"]) #here starting index will be string "1"
print(series_c[1]) #this will return implicit indexing output which is the 2nd element

10
20


<ipython-input-23-efa4e70f84f6>:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(series_c[1]) #this will return implicit indexing output which is the 2nd element


# Methods vs Functions:
Function is independent entity or not associated with any object
Method is asspciated with a specific class when called or invoked. It can manipulate object's state. Each libraty has specific methods and only they can be used for the object

In [24]:
start_date_deposits= pd.Series({
    '7/4/2014':24450,
    '1/2/2015':28900,
    '12/8/2012':43240,
    '2/20/2015':32450
})
print(start_date_deposits)

7/4/2014     24450
1/2/2015     28900
12/8/2012    43240
2/20/2015    32450
dtype: int64


In [25]:
#These methods are used both for Pandas and NumPy
print(start_date_deposits.sum()) #summing all the elements
print(start_date_deposits.min()) #minimum value
print(start_date_deposits.max()) #maximum value
print(start_date_deposits.idxmax()) #index of maximum value
print(start_date_deposits.idxmin()) #index of minimum value

129040
24450
43240
12/8/2012
7/4/2014


In [26]:
#These methods are used for Pandas only
print(start_date_deposits.head()) #gives first five elements
print((start_date_deposits.tail())) #gives last five elements

7/4/2014     24450
1/2/2015     28900
12/8/2012    43240
2/20/2015    32450
dtype: int64
7/4/2014     24450
1/2/2015     28900
12/8/2012    43240
2/20/2015    32450
dtype: int64


# Parameters and Arguments
Parameters can be used to modify method's performance. they are associated with methods
Arguments will be provided when executing
Things can be found in Pandas documentation also which can be found in web. Check the user guide of documentation part. In jupyter, use Shift+Tab for getting more info on a method

In [27]:
print(start_date_deposits.head(2)) #gives first 2 elements. 2 is here argument of head method

7/4/2014    24450
1/2/2015    28900
dtype: int64


In [28]:
print(start_date_deposits.head(n=2)) #gives first 2 elements. n is here parameter of head method. helpful when a method has multiple arguments

7/4/2014    24450
1/2/2015    28900
dtype: int64


## Panda DataFrame
Multi-Column Data representing different variable and datatype. We need two index here: one for row index and another column index. Single index will retuen only entire row or entire column.
We can provide a whole object that contains the values of an entire column to the dictionary keys.
Let's crete a dataframe from dictionary:

#Creating dataframe from single dictionary

In [29]:
data={'Productname':['Product A','Product B','Product C'],'ProductPrice':[22250,16600,12500]}
print(data)
df=pd.DataFrame(data) #default implicit indexing
print(df)

{'Productname': ['Product A', 'Product B', 'Product C'], 'ProductPrice': [22250, 16600, 12500]}
  Productname  ProductPrice
0   Product A         22250
1   Product B         16600
2   Product C         12500


In [30]:
#adding explicit labels: (label lengths must be same as no of elements)
df=pd.DataFrame(data,index=['A','B','C'])
print(df)

  Productname  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500


In [31]:
#adding index from another list
product_IDs=['A','B','C']
df= pd.DataFrame(data,index=product_IDs)
print(df)

  Productname  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500


#Creating dataframe of list of dictionaries:

In [32]:
#all columns will need data
data=[{'ProductName':'Product A','ProductPrice':22250},{'ProductName':'Product B','ProductPrice':16600},{'ProductName':'Product C','ProductPrice':12500}]
df=pd.DataFrame(data)
print(df)

  ProductName  ProductPrice
0   Product A         22250
1   Product B         16600
2   Product C         12500


#Creating Dataframe from Pandas Series:

In [33]:
ser_products=pd.Series(['Product A','Product B','Product C'])
ser_prices=pd.Series([22250,16600,12500])

data={'ProductName':ser_products,'ProductPrice':ser_prices}
df=pd.DataFrame(data)
print(df)

  ProductName  ProductPrice
0   Product A         22250
1   Product B         16600
2   Product C         12500


In [34]:
# Adding explicit index to this type of creation is bit different:
ser_products=pd.Series(['Product A','Product B','Product C'],index=['A','B','C'])
ser_prices=pd.Series([22250,16600,12500],index=['A','B','C'])

data={'ProductName':ser_products,'ProductPrice':ser_prices}
df=pd.DataFrame(data)
print(df)

#changing the index sequence for any of the pandas series, will eventually rearrange with corresponding Product name

  ProductName  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500


#Creating Dataframe from List of Lists

In [35]:
data=[
    ['Product A',22250],
    ['Product B',16600],
    ['Product C',12500]
]
df=pd.DataFrame(data)
print(df)
print('\n')
#adding columns and indices
df.columns=['ProductName','ProductPrice']
df.index=['A','B','C']
print(df)


           0      1
0  Product A  22250
1  Product B  16600
2  Product C  12500


  ProductName  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500


#The Professional way of creating DataFrame

In [36]:
df=pd.DataFrame(data=[
    ['Product A',22250],
    ['Product B',16600],
    ['Product C',12500]
],
columns=['ProductName','ProductPrice'],
index=['A','B','C'])

print(df)
print(df.shape)

  ProductName  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500
(3, 2)


check documentation--user guide--dataframe for more

##Data Cleaning and data Preprocessing
Pandas can be used for:
 i)Data preprocessing(data cleaning) which includes Re-categorization of data, Inputting missing values, Shuffling etc
ii)Data preparation which includes statistics,mathematics, visualization, predictive models

In [ ]:
#importing a csv file
data=pd.read.csv('filename.csv',squeeze=True) #squeeze is used to directly get the series values
location_data=data.copy() #To modify easily
location_data.head()

In [ ]:
#to get some stat about data:
location_data.describe()

print(len(location_data)) #gets the length
print(location_data.nunique()) #gets the number of unique values
print(location_data.unique()) #gets the unique values

#Converting Series into arrays:

In [42]:
prices_per_category=pd.Series({'Product A':22250,'Product B':16600,'Product C':15600})
print(prices_per_category)
prices_per_category.to_numpy()

Product A    22250
Product B    16600
Product C    15600
dtype: int64


array([22250, 16600, 15600])

other way to convert only certain elements:

In [47]:
test_array=prices_per_category[['Product A','Product B']].to_numpy(dtype='float')
print(test_array)
print('\n')
print(prices_per_category.to_numpy()[0]) #getting only first element

[22250. 16600.]


22250


#Sort Values

In [49]:
numbers=pd.Series([15,1000,23,45,444])
print(numbers)
print('\n')
print(numbers.sort_values()) #ascending order by
print('\n')
print(numbers.sort_values(ascending=False)) #descending order

0      15
1    1000
2      23
3      45
4     444
dtype: int64


0      15
2      23
3      45
4     444
1    1000
dtype: int64


1    1000
4     444
3      45
2      23
0      15
dtype: int64


#Attribure and Method Chaining

In [ ]:
#importing a csv file
data=pd.read.csv('filename.csv',squeeze=True) #squeeze is used to directly get the series values
location_data=data.copy() #To modify easily
location_data.head()

In [ ]:
location_data.index #gives the index allthe data
print(location_data.name) #returns the name of the column or the attribute

In [ ]:
location_data.index.name='Index' #gives name Index to the range of indices column

In [ ]:
location_data.sort_values() #sorts all the data
location_data.sort_values().head() #sorts first 5 elements
location_data.sort_values.tail() #sorts last 5 elements

# Method chaining:
organizes and applies several method calls on a certain object in a given order

In [ ]:
location_data.index.to_numpy() #converts to numpy array all the indices

# Sort_index:
We will combine chaining technique and assignment technique

In [ ]:
location_data.sort_values(ascending=False)
location_data_sv=location_data.sort_values(ascending=False) #sorts according to the location values
location_data_sv.head()

In [ ]:
location_data_sv.index.sort_values() #sorts according to values

In [ ]:
location_data_sv.sort_index() #sorts the index

#DataFrames:
Just a data table

In [1]:
import numpy as np
import pandas as pd

In [2]:
array_a=np.array([[3,2,1],[6,3,2]])
print(array_a)
pd.DataFrame(array_a)

[[3 2 1]
 [6 3 2]]


,0,1,2
0,3,2,1
1,6,3,2


from matplotlib import pyplot as plt
_df_0[0].plot(kind='hist', bins=20, title=0)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1[1].plot(kind='hist', bins=20, title=1)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2[2].plot(kind='hist', bins=20, title=2)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3.plot(kind='scatter', x=0, y=1, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x=1, y=2, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[0]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 0}, axis=1)
              .sort_values(0, ascending=True))
  xs = counted[0]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_5.sort_values(0, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(0)
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[1]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 1}, axis=1)
              .sort_values(1, ascending=True))
  xs = counted[1]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_6.sort_values(1, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(1)
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[2]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 2}, axis=1)
              .sort_values(2, ascending=True))
  xs = counted[2]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_7.sort_values(2, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(2)
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_8[0].plot(kind='line', figsize=(8, 4), title=0)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9[1].plot(kind='line', figsize=(8, 4), title=1)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10[2].plot(kind='line', figsize=(8, 4), title=2)
plt.gca().spines[['top', 'right']].set_visible(False)

In [4]:
df=pd.DataFrame(array_a,columns=['Column 1','Column 2','Column 3'],index=['Row 1','Row 2'])
print(df)

       Column 1  Column 2  Column 3
Row 1         3         2         1
Row 2         6         3         2


In [12]:
print(df.index) #returns index names/no
print(df.columns) #returns column names
print(df.axes)#returns both index and column names
print(df.dtypes) #returns datatype of each column
print(df.values) #returns only values
print(df.shape) #returns no. of rows and columns. Index column is not included

Index(['Row 1', 'Row 2'], dtype='object')
Index(['Column 1', 'Column 2', 'Column 3'], dtype='object')
[Index(['Row 1', 'Row 2'], dtype='object'), Index(['Column 1', 'Column 2', 'Column 3'], dtype='object')]
Column 1    int64
Column 2    int64
Column 3    int64
dtype: object
[[3 2 1]
 [6 3 2]]
(2, 3)


In [11]:
df.to_numpy()#converts every row to numpy

array([[3, 2, 1],
       [6, 3, 2]])

#Data selction in Pandas dataFrame
Extracts certain data from full dataset

In [ ]:
data=pd.read_csv('Lending-company.csv',index_col='LoanID')
lending_co_data=data.copy()

In [ ]:
lending_co_data.Product #will return the product column
lending_co_data['Product'] #will return the product column using indexing operator. More used
lending_co_data=[['Product','Location']] #will return the product and location column. Needs two bracktes

#more good way:
prod_loc=['Product','Location']
lending_co_data[prod_loc].head()

#iloc[ ] indexers:
Used as accessor.

In [ ]:
lending_co_data.iloc[1] #will return 2nd row
lending_co_data.iloc[1,3] #will return 4th info of 2nd row

In [ ]:
lending_co_data.iloc[1:4,:] #will return 2nd to 4th row

#.loc[ ] accessor:
sub select information from a DataFrame by referring to its index labels

In [ ]:
lending_co_data.loc['LoadID_3',:] # will return entire row of load ID 3
lending_co_data.loc['Load_ID3','Location']    #will return interest rate of load ID 3
lending_co_data.loc[:,'Location'] #will return all the locations